### ISSUE TITLE
MDUI

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/federationregistry#8]
Some REFEDS recommendations for MDUI 

```
     https://refeds.terena.org/index.php/MDUI_-_Software_recommendations
```

and    https://refeds.terena.org/index.php/MDUI_-_Federation_recommendations

**Comment by vladimir-mencl-eresearch** [comment]
Hi Bradley,

FYI, the URLs have moved to:
* https://wiki.refeds.org/display/FBP/MDUI+-+Software+recommendations
* https://wiki.refeds.org/display/FBP/MDUI+-+Federation+recommendations

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
FYI, this is starting to be (mildly) pressing because IdPV3 is (partly) moving away from AttributeConsumingService.ServiceName and would rather parse mdui:UIInfo

It's so far affecting just the logout page - I tried filing a bug report for not getting displayName on the logout page (IDP-723 [1]); the reaction I got (from Scott C.) was that AttributeConsumingService is not the way to do this. 
> The ACS was never meant to be used like this, so the basic answer is, populate the UIInfo extension if you want UI material. 

I just started looking into this, I think the information we have in the FR would be enough to populate mdui:DisplayName and mdui:Description (and we would set the language to system-wide config value, typically "en").

We would not be able to do mdui:Logo, as we do not have the logo sizes, just the URL (and not always).  And trying a background task to fetch all logos and determine sizes sounds nightmarish...

I'm thinking about tackling this in a similar way as I did mdrpi.  Would you be interested in merging the code if I sent you a pull request?

It would be just a subset of mdui, but it would make IdPV3 (and the eduGAIN validator) happy - and I'd of course make it configurable, so that you can switch it off (and have it off by default).

Any thoughts?

Cheers,
Vlad

[1]: https://issues.shibboleth.net/jira/browse/IDP-723

**Comment by bradleybeddoes** [comment]
Thanks Vlad - MDUI is implemented as part of saml-service https://github.com/ausaccessfed/saml-service/pull/27 (development ongoing in other areas, no completion eta yet).

Whatever the future tool looks like to collate data required by MDUI we're good to go in terms of the actual XML.

**Comment by bradleybeddoes** [comment]
Happy to consider code to:

    populate mdui:DisplayName and mdui:Description (and we would set the language to system-wide config value, typically "en")

As an interim measure, assuming off by default as you propose.

**Comment by vladimir-mencl-eresearch** [comment]
Ref pull request #196

**Comment by vladimir-mencl-eresearch** [comment]
@bradleybeddoes  ... just stumbled across this.  With #196 merged (long ago), should be this considered done?

**Comment by bradleybeddoes** [comment]
Yep
